### ISSUE TITLE
Any news regarding it?

### ISSUE THREAD

**Issue by Zero3K** [cocus/openmsvbvbm#2]
*subject*

**Comment by cocus** [comment]
Well, the project is kinda stalled. The last time I worked on it was a rewrite of the part that parses objects like forms and classes since I figured out that they have a complex structure, and they seem to share it. What I've managed to do with my classes example over here is actually wrong, and it doesn't uses the proper structures.
I would like to have some help of other contributors since it's pretty hard to manage all these unknowns by myself, and I can't put that much time into reverse engineering things.
If you can help me out, or you know someone who might be interested, we can create a discord server and follow up over there.

**Comment by Zero3K** [comment]
I can't help out and I don't know of anyone.

**Comment by cocus** [comment]
well, until I have a free moment to work thoroughly on it, I assume there will be no news :(
I'm still looking forward for more people that wants to contribute to this project.

**Comment by Zero3K** [comment]
You can try asking on Reddit (such as on /r/programming, /r/opensource, etc).

**Comment by minecraftchest1** [comment]
This was mentioned by @zero3k on chat.reactos.org,so someone there may help as well.
